
# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    connection-timeout: 5000
    servlet:
        context-path: /hsys

spring:
    #profiles: # 环境 dev
    #    active: dev
    #aop:
    #  auto: true
    jackson: # jackson时间格式化
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
            enabled: true
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,file:///c:/hsys/upload/ #最后一个是上传文件的路径，参照hsys.upload.location
    mvc: 
        static-path-pattern: /**
    datasource: # 数据库配置
        url: jdbc:mysql://localhost:3306/hsys?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: root
        driverClassName: com.mysql.jdbc.Driver
    thymeleaf: #thymeleaf
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML
        encoding: UTF-8
        cache: false #turn off when in developing or cant refresh immdiately
        servlet:
            content-type: text/html

#log配置
logging: 
    level:
        org.springframework.web: WARN
        com.hsys.mappers: DEBUG
        com.hsys: INFO
    file: c:/hsys/log/hsys.log
     
# Mybatis配置
mybatis:
    mapperLocations: classpath:mappers/*.xml
    type-aliases-package: com.hsys.models,com.hsys.mappers
    configuration:
        map-underscore-to-camel-case: true

#hsys其余设定
hsys:
    version:
        number: v.HSYS2019.0
    upload: 
        temp-folder: c:/hsys/upload/temp #临时文件夹
        attendance-folder: c:/hsys/upload/attendance #考勤信息文件夹
        receipt-attachment-folder: c:/hsys/upload/receipt-attachment-folder #报销单附件文件夹
    backup: #备份设定
        database:
            enable: true
            location: D:\dev\hsys\env\mysql-5.7.21-winx64\bin\ #mysql安装bin路径
            backupDir: c:/hsys/dbbackup
            host: localhost
            name: hsys
            username: root
            password: root
  
